apiVersion: v1
data:
 TCP_HOST: 0.0.0.0
 TCP_PORT: "3010"
 MYSQL_DB_USER: transport_prod
 MYSQL_DB_PASSWORD: HufmN4tmXmY2FEkY
 MYSQL_DB_PORT: "3306"
 MYSQL_DB_HOST: 172.16.11.165
 MYSQL_DB: transport-prod
 KAFKA_HOST: kafka.production:9092
 REDIS_HOST: redis.production
 REDIS_PORT: "6379"
 EWALLET_CHANNEL: APP
 EWALLET_USERNAME: transportation
 EWALLET_PASSWORD: tSqj7Ny2F7R9gdtyLD56
 EWALLET_API_URL: https://live.loop.sa/billers/rest/v2
 EWALLET_SP_ID: bayanpay
 FCM_SERVER_KEY: AAAAVWo08ww:APA91bGIdwRG__lHZwaW8w2W8MDvN2w7S__jpi1CNqecGMDegCOANsV-tyFxt_6Ikm9UTOgvmV-rduGLzAw8PLOaXUUa0d862pN20i2jKoHXW7lrTEDYNJIa3-_YaRiJsJ-BCZtiJ23_
 S3_TRANSPORT_ACCESS_URL: https://loop-transportation-prod.s3.me-south-1.amazonaws.com
 SMTP_HOST: "93.189.101.20"
 SMTP_PORT: "25"
 SMTP_SECURE: "false"
 SMTP_USERNAME: "customerservice@bayanwallet.com"
 SMTP_PASSWORD: "Fuz52265"
 LOG_MODE: production
kind: ConfigMap
metadata:
  name: notifications-service-config
  namespace: production-notification

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-service-deployment
  namespace: production-notification
spec:
  selector:
    matchLabels:
      app: notifications-service
  template:
    metadata:
      labels:
        app: notifications-service
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: notifications-service-config
        image: registry.gitlab.com/loopwallet/loop_transportation_backend/notifications-service-production:latest
        imagePullPolicy: Always
        name: notifications-service
        ports:
        - containerPort: 8003
      imagePullSecrets:
      - name: gitlab-registry
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-service-svc
  namespace: production-notification
spec:
  selector:
    app: notifications-service
  ports:
    - name: app-port
      port: 8003
      targetPort: 8003
    - name: tcp
      protocol: TCP
      port: 3010
      targetPort: 3010