apiVersion: v1
data:
 TCP_PORT: "3003"
 TCP_HOST: 0.0.0.0
 MYSQL_DB_USER: transport_preprod
 MYSQL_DB_PASSWORD: GMNbcsHS4NEmh5ND
 MYSQL_DB_PORT: "3306"
 MYSQL_DB_HOST: 172.16.11.170
 MYSQL_DB: transport-preprod
 KAFKA_HOST: kafka.preprod:9092
 REDIS_HOST: redis-preprod.preprod
 REDIS_PORT: "6379"
 S3_BUCKET: loop-captain-preprod
 S3_REGION: me-south-1
 S3_ACCESS_KEY: AKIAVAG4SUALG34WJMGL
 S3_SECRET_KEY: 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
 S3_ACCESS_URL: https://loop-captain-preprod.s3.me-south-1.amazonaws.com
 ADMIN_BASE_URL: https://admin-qa.loop.sa
 ADMIN_RESETLINK_EXPIRY_TIME: "48"
 LOG_MODE: production
kind: ConfigMap
metadata:
  name: admin-service-config
  namespace: preprod-admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service-deployment
  namespace: preprod-admin
spec:
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: admin-service-config
        image: registry.gitlab.com/loopwallet/loop_transportation_backend/admin-service-preprod:latest
        imagePullPolicy: Always
        name: admin-service
        ports:
        - containerPort: 8007
      imagePullSecrets:
      - name: gitlab-registry
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service-svc
  namespace: preprod-admin
spec:
  selector:
    app: admin-service
  ports:
    - name: app-port
      port: 8007
      targetPort: 8007
    - name: tcp
      protocol: TCP
      port: 3003
      targetPort: 3003
