apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: k8s.io/minikube-hostpath
  name: notifications-service-mysql-pv-claim-preprod
  namespace: preprod-notification    
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: notifications-service-mysql-pv-claim-preprod
    namespace: preprod-notification
  hostPath:
    path: /tmp/hostpath-provisioner/preprod-notification/notifications-service-mysql-pv-claim-preprod
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
