apiVersion: v1
kind: PersistentVolume
metadata:
  name: promo-code-service-mysql-pv-claim
  namespace: dev
  annotations:
    pv.kubernetes.io/provisioned-by: k8s.io/minikube-hostpath
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: promo-code-service-mysql-pv-claim
    namespace: dev
  hostPath:
    path: /tmp/hostpath-provisioner/dev/promo-code-service-mysql-pv-claim
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
