apiVersion: v1
kind: PersistentVolume
metadata:
  name: promo-code-service-mysql-pv-claim-preprod
  namespace: preprod-promo
  annotations:
    pv.kubernetes.io/provisioned-by: k8s.io/minikube-hostpath
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: promo-code-service-mysql-pv-claim-preprod
    namespace: preprod-promo
  hostPath:
    path: /tmp/hostpath-provisioner/preprod-promo/promo-code-service-mysql-pv-claim-preprod
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
