apiVersion: v1
data:
 DB_HOST: 172.16.11.110:27017
 DB_USER: chat-dev
 DB_PASSWORD: NEQqB8KgJNxYa6Tm
 DB_NAME: chat-dev
 KAFKA_HOST: kafka.dev:9092
 REDIS_HOST: redis-uat.dev
 REDIS_PORT: "6379"
 SOCKET_PORT: "8100"
 REVIEW_TCP_PORT: "3009"
 REVIEW_TCP_HOST: "reviews-service-svc.dev"
 LOG_MODE: development
 S3_BUCKET: loop-captain-uat
 S3_CHAT_BUCKET: loop-chat-uat
 S3_PUBLIC_BUCKET: loop-transportation-uat
 S3_ACCESS_URL: https://loop-captain-uat.s3.me-south-1.amazonaws.com
 S3_CHAT_ACCESS_URL: https://loop-chat-uat.s3.me-south-1.amazonaws.com
 S3_PUBLIC_ACCESS_URL: https://loop-transportation-uat.s3.me-south-1.amazonaws.com

kind: ConfigMap
metadata:
  name: chat-service-config
  namespace: dev-chat

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service-deployment
  namespace: dev-chat
spec:
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: chat-service-config
        image: registry.gitlab.com/loopwallet/loop_transportation_backend/chat-service:latest
        imagePullPolicy: Always
        name: chat-service
        ports:
        - containerPort: 8013
      imagePullSecrets:
      - name: gitlab-registry
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service-svc
  namespace: dev-chat
spec:
  selector:
    app: chat-service
  ports:
    - name: app-port
      port: 27017
      targetPort: 27017
