import { registerAs } from '@nestjs/config';
require('dotenv').config();

export default registerAs('app', () => ({
  apiPort: process.env.API_PORT,
  TripTCPHost: process.env.TRIP_TCP_HOST,
  TripTcpPort: process.env.TRIP_TCP_PORT,
  KafkaHost: process.env.KAFKA_HOST,
  RedisHost: process.env.REDIS_HOST,
  RedisPort: process.env.REDIS_PORT,
  TCPHost: process.env.TCP_HOST,
  TCPPort: process.env.TCP_PORT,
  proxyHost: process.env.PROXY_HOST,
  proxyPort: parseInt(process.env.PROXY_PORT),
  proxyMode: parseInt(process.env.PROXY_MODE),
  ibanKey: process.env.IBAN_KEY,
  ibanApiUrl: process.env.IBAN_API_URL,
  CaptainTCPHost: process.env.CAPTAIN_TCP_HOST,
  CaptainTCPPort: process.env.CAPTAIN_TCP_PORT,
  paymentAPIUrl: process.env.EWALLET_PAYMENT_URL,
  subscriptionAPIUrl: process.env.EWALLET_SUBSCRIPTION_URL,
  paymentChannel: process.env.EWALLET_PAYMENT_CHANNEL,
  paymentAPIUser: process.env.EWALLET_PAYMENT_USER,
  paymentAPIPass: process.env.EWALLET_PAYMENT_PASS,
  subscriptionAPIUser: process.env.EWALLET_SUBSCRIPTION_USER,
  subscriptionAPIPass: process.env.EWALLET_SUBSCRIPTION_PASS,
  logMode: process.env.LOG_MODE,
  clickPayAuth: process.env.CLICK_PAY_AUTH,
  clickPayBaseurl: process.env.CLICK_PAY_BASE_URL,
  clickPayCallbackUrl: process.env.CLICK_PAY_CALLBACK_URL,
  clickPayPorfileId: process.env.CLICK_PAY_PORFILE_ID,
  sellerName: process.env.SELLER_NAME,
  vatRegistrationNo: process.env.VAT_REGISTRATION_NO,
  sellerAddress: process.env.SELLER_ADDRESS,

  alinmaMainAccNum: process.env.ALINMA_MAIN_ACC,
  alinmaTopupAccNum: process.env.ALINMA_TOPUP_ACC,
  alinmaSubscriptionAccNum: process.env.ALINMA_SUBSCRIPTION_ACC,
  alinmaRideTopupAccNum: process.env.ALINMA_RIDE_TOPUP_ACC,
  alinmaFeeAccNum: process.env.ALINMA_FEE_ACC,
  alinmaTaxAccNum: process.env.ALINMA_TAX_ACC,

  alinmaAccInqFuncId: process.env.ALINMA_ACC_INQ_FUNC_ID,
  alinmaDlvrblDtlsFuncId: process.env.ALINMA_DLVRBL_DTLS_INQ_FUNC_ID,
  alinmaDlvrblInqFuncId: process.env.ALINMA_DLVRBL_INQ_FUNC_ID,
  alinmaXferBtwCustFuncId: process.env.ALINMA_XFER_BTW_CUST_FUNC_ID,
  alinmaXferSarieFuncId: process.env.ALINMA_XFER_SARIE_FUNC_ID,
  alinmaXferAlinmaFuncId: process.env.ALINMA_XFER_ALINMA_FUNC_ID,

  alinmaAccInqUrl: process.env.ALINMA_ACC_INQ_URL,
  alinmaDlvrblDtlsUrl: process.env.ALINMA_DLVRBL_DTLS_INQ_URL,
  alinmaDlvrblInqUrl: process.env.ALINMA_DLVRBL_INQ_URL,
  alinmaXferBtwCustUrl: process.env.ALINMA_XFER_BTW_CUST_URL,
  alinmaXferSarieUrl: process.env.ALINMA_XFER_SARIE_URL,
  alinmaXferAlinmaUrl: process.env.ALINMA_XFER_ALINMA_URL,

  alinmaJksPath: process.env.ALINMA_JKS_PATH,
  alinmaJksPass: process.env.ALINMA_JSK_PASS,

  alinmaCertPath: process.env.ALINMA_CERT_PATH,
  alinmaKeyPath: process.env.ALINMA_KEY_PATH,
  alinmaEncryptedKeyPath: process.env.ALINMA_ENCRYPTED_KEY_PASS,
  alinmaKeyPass: process.env.ALINMA_KEY_PASS,

  alinmaPartnerId: process.env.ALINMA_PARTNER_ID,
  alinmaChannelId: process.env.ALINMA_CHANNGEL_ID,

  wssePhpScriptPath: process.env.WSSE_PHP_SCRIPT_PATH,
}));
