apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: k8s.io/minikube-hostpath
  name: captain-service-mysql-pv-claim
  namespace: production-captain  
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: captain-service-mysql-pv-claim
    namespace: production-captain
  hostPath:
    path: /tmp/hostpath-provisioner/production-captain/captain-service-mysql-pv-claim
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
