apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: admin-service-db-deployment
  namespace: production-admin
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:8.0.20
          name: mysql
          env:
            - name: MYSQL_DATABASE
              value: transport-prod
            - name: MYSQL_USER
              value: app
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: mysql-secrets
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: mysql-secrets                
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: admin-service-mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: admin-service-mysql-persistent-storage
          persistentVolumeClaim:
            claimName: admin-service-mysql-pv-claim-production
      imagePullSecrets:
        - name: gitlab-registry
---
apiVersion: v1
kind: Service
metadata:
  name: admin-mysql-service
  namespace: production-admin
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: admin-service-mysql-pv-claim-production
  namespace: production-admin
spec: 
  accessModes:
    - ReadWriteOnce 
  resources: 
    requests:
      storage: 10Gi
