apiVersion: v1
kind: PersistentVolume
metadata:
  name: reviews-service-mysql-pv-claim-preprod
  namespace: preprod-review
  annotations:
    pv.kubernetes.io/provisioned-by: k8s.io/minikube-hostpath
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: reviews-service-mysql-pv-claim-preprod
    namespace: preprod-review
  hostPath:
    path: /tmp/hostpath-provisioner/preprod-review/reviews-service-mysql-pv-claim-preprod
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
