apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: k8s.io/minikube-hostpath
  name: captain-service-mysql-pv-claim-preprod
  namespace: preprod-captain    
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: captain-service-mysql-pv-claim-preprod
    namespace: preprod-captain
  hostPath:
    path: /tmp/hostpath-provisioner/preprod-captain/captain-service-mysql-pv-claim-preprod
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem