version: '3.4'

services:
    db:
      container_name: transportation_db
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: uJIpc#4ACZA
        MYSQL_DATABASE: transportation_db
      ports:
        - "3307:3306"
      expose:
        - "3307"

    phpmyadmin:
      container_name: transportation_db_phpmyadmin
      image: phpmyadmin/phpmyadmin
      links: 
          - db:db
      ports:
          - 8001:80
      expose: 
        - "8001"
      environment:
          PMA_PORT: 3307
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: uJIpc#4ACZA
          MYSQL_DATABASE: transportation_db