apiVersion: v1
data:
 API_PORT: "3016"
 TCP_HOST: 0.0.0.0
 TCP_PORT: "3006"
 PROMO_CODES_TCP_HOST: "promo-code-service-svc.dev"
 PROMO_CODES_TCP_PORT: "3005"
 CAPTAIN_TCP_HOST: "captain-service-svc.dev-captain"
 CAPTAIN_TCP_PORT: "3004"
 PAYMENT_TCP_HOST: "payment-service-svc.dev-payment"
 PAYMENT_TCP_PORT: "3007"
 REVIEW_TCP_HOST: "reviews-service-svc.dev"
 REVIEW_TCP_PORT: "3009"
 MYSQL_DB_USER: transport_uat
 MYSQL_DB_PASSWORD: hNwbVfsjwum9pJvd
 MYSQL_DB_PORT: "3306"
 MYSQL_DB_HOST: 172.16.11.170
 MYSQL_DB: transport-uat
 KAFKA_HOST: kafka.dev:9092
 GOOGLE_KEY: AIzaSyAJWpL90sZNJR0nU8FPowP0H4LkH-5I0qc
 REDIS_HOST: redis-uat.dev
 REDIS_PORT: "6379"
 S3_BUCKET: loop-captain-uat
 S3_REGION: me-south-1
 S3_ACCESS_KEY: AKIAVAG4SUALG34WJMGL
 S3_SECRET_KEY: 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
 S3_ACCESS_URL: https://loop-captain-uat.s3.me-south-1.amazonaws.com
 LOG_MODE: production
kind: ConfigMap
metadata:
  name: trip-service-config
  namespace: dev-trip

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-service-deployment
  namespace: dev-trip
spec:
  selector:
    matchLabels:
      app: trip-service
  template:
    metadata:
      labels:
        app: trip-service
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: trip-service-config
        image: registry.gitlab.com/loopwallet/loop_transportation_backend/trip-service:latest
        imagePullPolicy: Always
        name: trip-service
        ports:
        - containerPort: 8006
      imagePullSecrets:
      - name: gitlab-registry
---
apiVersion: v1
kind: Service
metadata:
  name: trip-service-svc
  namespace: dev-trip
spec:
  selector:
    app: trip-service
  ports:
    - name: app-port
      port: 8006
      targetPort: 8006
    - name: tcp
      protocol: TCP
      port: 3006
      targetPort: 3006
