apiVersion: v1
data:
 CAPTAIN_TCP_HOST: "captain-service-svc.dev-captain"
 CAPTAIN_TCP_PORT: "3004"
 TRIP_TCP_HOST: "trip-service-svc.dev-trip"
 TRIP_TCP_PORT: "3006"
 ADMIN_TCP_HOST: "admin-service-svc.dev-admin"
 ADMIN_TCP_PORT: "3003"
 SOCKET_PORT: "8100"
 REDIS_HOST: redis-uat.dev
 REDIS_PORT: "6379"
 SOCKET_URL: ""
 KAFKA_HOST: kafka.dev:9092
kind: ConfigMap
metadata:
  name: socket-gateway-service-config
  namespace: dev-socket

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-gateway-service-deployment
  namespace: dev-socket
spec:
  selector:
    matchLabels:
      app: socket-gateway-service
  template:
    metadata:
      labels:
        app: socket-gateway-service
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: socket-gateway-service-config
        image: registry.gitlab.com/loopwallet/loop_transportation_backend/socket-service:latest
        imagePullPolicy: Always
        name: socket-gateway-service
        ports:
        - containerPort: 8100
      imagePullSecrets:
      - name: gitlab-registry
---
apiVersion: v1
kind: Service
metadata:
  name: socket-gateway-service-svc
  namespace: dev-socket
spec:
  selector:
    app: socket-gateway-service
  ports:
    - name: app-port
      port: 8100
      targetPort: 8100
