apiVersion: v1
data:
 CAPTAIN_TCP_PORT: "3004"
 CAPTAIN_TCP_HOST: "captain-service-svc.production-captain"
 TRIP_TCP_PORT: "3006"
 TRIP_TCP_HOST: "trip-service-svc.production-trip"
 PROMO_CODES_TCP_PORT: "3005"
 PROMO_CODES_TCP_HOST: "promo-code-service-svc.production-promo-code"
 ADMIN_TCP_PORT: "3003"
 ADMIN_TCP_HOST: "admin-service-svc.production-admin"
 PAYMENT_TCP_PORT: "3007"
 PAYMENT_TCP_HOST: "payment-service-svc.production-payment"
 REVIEW_TCP_PORT: "3009"
 REVIEW_TCP_HOST: "reviews-service-svc.production-reviews"
 AUTH_TCP_PORT: "3008"
 AUTH_TCP_HOST: "auth-service-svc.production-auth"
 NOTIFICATION_TCP_PORT: "3010"
 NOTIFICATION_TCP_HOST: "notifications-service-svc.production-notification"
 KAFKA_HOST: kafka.production:9092
 JWT_EXPIRES: "60m"
 JWT_SECRET: WnIcknAdqOtJysuTKjZWK4UWGtJzPGe8
 REDIS_HOST: redis.production
 REDIS_PORT: "6379"
 API_PORT: "3000"
 SESSION_EXPIRE_TIME: "20"
 S3_BUCKET: loop-captain-prod
 S3_CHAT_BUCKET: loop-chat-prod
 S3_REGION: me-south-1
 S3_ACCESS_KEY: AKIAVAG4SUALG34WJMGL
 S3_SECRET_KEY: 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
 S3_ACCESS_URL: https://loop-captain-prod.s3.me-south-1.amazonaws.com
 S3_CHAT_ACCESS_URL: https://loop-chat-prod.s3.me-south-1.amazonaws.com
 SMTP_HOST: "93.189.101.20"
 SMTP_PORT: "25"
 SMTP_SECURE: "false"
 SMTP_USERNAME: "customerservice@bayanwallet.com"
 SMTP_PASSWORD: "Fuz52265"
 LOG_MODE: production
kind: ConfigMap
metadata:
  name: api-service-config
  namespace: production-api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service-deployment
  namespace: production-api
spec:
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: api-service-config
        image: registry.gitlab.com/loopwallet/loop_transportation_backend/api-service-production:latest
        imagePullPolicy: Always
        name: api-service-config
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: gitlab-registry
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service-svc
  namespace: production-api
spec:
  selector:
    app: api-gateway-service
  ports:
    - name: app-port
      port: 3000
      targetPort: 3000
